#    \\ SPIKE: Secure your secrets with SPIFFE.
#  \\\\\ Copyright 2024-present SPIKE contributors.
# \\\\\\\ SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: spike-edge
  name: spike-keeper
  labels:
    app.kubernetes.io/name: spike-keeper
    app.kubernetes.io/component: keeper
    app.kubernetes.io/part-of: spike
    app.kubernetes.io/version: "0.4.0"
spec:
  serviceName: spike-keeper-headless
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: spike-keeper
      app.kubernetes.io/component: keeper
  template:
    metadata:
      namespace: spike-edge
      labels:
        app.kubernetes.io/name: spike-keeper
        app.kubernetes.io/component: keeper
        app.kubernetes.io/part-of: spike
        app.kubernetes.io/version: "0.4.0"
    spec:
      serviceAccountName: spike-keeper
      containers:
      - name: app
        image: localhost:5000/spike-keeper:0.4.0
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        ports:
        - containerPort: 8443
          name: api
        env:
        - name: SPIKE_TRUST_ROOT
          value: spike.ist
        - name: SPIKE_SYSTEM_LOG_LEVEL
          value: DEBUG
        - name: SPIFFE_ENDPOINT_SOCKET
          value: "unix:///spiffe-workload-api/spire-agent.sock"
        volumeMounts:
        - name: spiffe-workload-api
          mountPath: /spiffe-workload-api
          readOnly: true
      volumes:
      - name: spiffe-workload-api
        csi:
          driver: "csi.spiffe.io"
          readOnly: true
