#    \\ SPIKE: Secure your secrets with SPIFFE.
#  \\\\\ Copyright 2024-present SPIKE contributors.
# \\\\\\\ SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  namespace: spike-edge
  name: spike-keeper-headless
  labels:
    app.kubernetes.io/name: spike-keeper
    app.kubernetes.io/component: keeper
    app.kubernetes.io/part-of: spike
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: spike-keeper
    app.kubernetes.io/component: keeper
  ports:
    - port: 8443
      name: api
