#    \\ SPIKE: Secure your secrets with SPIFFE.
#  \\\\\ Copyright 2024-present SPIKE contributors.
# \\\\\\\ SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: spike-system
  name: spike-nexus
  labels:
    app.kubernetes.io/name: spike-nexus
    app.kubernetes.io/component: nexus
    app.kubernetes.io/part-of: spike
    app.kubernetes.io/version: "0.4.0"
spec:
  serviceName: spike-nexus-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spike-nexus
      app.kubernetes.io/component: nexus
  template:
    metadata:
      namespace: spike-system
      labels:
        app.kubernetes.io/name: spike-nexus
        app.kubernetes.io/component: nexus
        app.kubernetes.io/part-of: spike
        app.kubernetes.io/version: "0.4.0"
    spec:
      serviceAccountName: spike-nexus
      containers:
      - name: app
        image: localhost:32000/spike-nexus:0.4.0
        ports:
        - containerPort: 8553
          name: api
        env:
        - name: SPIKE_TRUST_ROOT
          value: spike.ist
        - name: SPIKE_SYSTEM_LOG_LEVEL
          value: DEBUG
        - name: SPIFFE_ENDPOINT_SOCKET
          value: "unix:///spiffe-workload-api/spire-agent.sock"
      volumes:
      - name: spiffe-workload-api
        csi:
          driver: "csi.spiffe.io"
          readOnly: true
