#    \\ SPIKE: Secure your secrets with SPIFFE.
#  \\\\\ Copyright 2024-present SPIKE contributors.
# \\\\\\\ SPDX-License-Identifier: Apache-2.0

apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: spike-keeper
  labels:
    app.kubernetes.io/name: spike-keeper
    app.kubernetes.io/component: keeper
    app.kubernetes.io/part-of: spike
spec:
  className: "spire-server-spire"
  spiffeIDTemplate: "spiffe://spike.ist/spike/keeper/{{ .PodMeta.Name }}"
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: spike-edge
  podSelector:
    matchLabels:
      app.kubernetes.io/name: spike-keeper
      app.kubernetes.io/component: keeper
